---
driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2204-ansible}
    pre_build_image: true
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    user: root
    environment:
      HOME: /root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp:rw,mode=1777   # <— essentiel : /tmp en écriture avec bons perms
    # Optionnel: pour voir le dashboard depuis ton host pendant les tests locaux
    published_ports:
      - "8080:8080"   # http://localhost:8080/dashboard/
      - "80:80"
provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      remote_tmp: /tmp/.ansible/tmp
  inventory:
    host_vars:
      instance:
        ansible_connection: docker
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: converge.yml
    verify: verify.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: "${MOLECULE_EPHEMERAL_DIRECTORY}/roles"
    force: true

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

